# Generated by Django 3.2.8 on 2021-10-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0002_auto_20211011_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='recipe_category', to='recipeapp.Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.RemoveField(
            model_name='category',
            name='recipe',
        ),
        migrations.AddField(
            model_name='category',
            name='recipe',
            field=models.ManyToManyField(related_name='categories', to='recipeapp.Recipe'),
        ),
    ]
