# Generated by Django 3.2.8 on 2021-10-11 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0003_auto_20211011_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='recipe',
        ),
    ]
