# Generated by Django 3.2.8 on 2021-10-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0007_alter_recipe_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Ingredients',
        ),
    ]
