# Generated by Django 3.2.8 on 2021-10-20 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0008_auto_20211015_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='approval',
            new_name='approved',
        ),
    ]
