# Generated by Django 3.2.8 on 2021-10-21 15:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipeapp', '0009_rename_approval_recipe_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='saved',
            field=models.ManyToManyField(blank=True, related_name='saved_recipes', to=settings.AUTH_USER_MODEL),
        ),
    ]
