# Generated by Django 3.2.8 on 2021-10-28 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0010_recipe_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
