# Generated by Django 3.2.8 on 2021-11-02 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0012_recipe_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='about',
            field=models.TextField(),
        ),
    ]
